apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: roboshop
  labels:
    project: roboshop
    component: debug
spec:
  containers:
    - name: debug
      image: narayanareddy2026/debug:v1  