apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue-config
  namespace: roboshop
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/catalogue" 

---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    component: mongodb
    environment: dev
    tier: db
spec:
  replicas: 1
  selector:
    matchlabels:
      project: roboshop
      component: mongodb
      environment: dev
      tier: db
  template:
  metadata:
    labels:
      project: roboshop
      component: mongodb
      environment: dev
      tier: db       
  spec:
    containers:
    - name: catalogue
      image: narayanareddy2026/catalogue:v1  
      imagePullPolicy: Always
      envFrom:
        - name: catalogue-config
      ports:
        - name: liveness-port
          containerPort: 8080
      readinessProbe:
          httpGet: 
            path: /health
            port: 8080
          failureThreshold: 1
          periodSeconds: 15
      livenessProbe:
          httpGet: 
            path: /health
            port: 8080
          failureThreshold: 1
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: redis
    environment: dev
    tier: backend
  ports:
    - port: 8080
      targetPort: 8080 

      

         